const permissions = {
  SalesRep: [
    "canViewLandingPage",
    "canViewActionPage",
    "canViewScoreCardPage",
    "canViewPicosDeepdive",
    "canViewOOSDeepdive",
    "canViewOSADeepdive",
    "canViewFeedback",
    "canViewGlossary",
  ],
  GlobalUser: [
    "canViewLandingPage",
    "canViewPicosDeepdive",
    "canViewOOSDeepdive",
    "canViewExecutiveSummaryGlobal",
    "canViewExecutiveSummary",
    "canViewOSADeepdive",
    "canViewMarketLeader",
    "canViewCountryLeader",
    "canViewFeedback",
    "canViewGlossary",
  ],
  SalesManager: [
    "canViewLandingPage",
    "canViewActionPage",
    "canViewScoreCardPage",
    "canViewPicosDeepdive",
    "canViewOOSDeepdive",
    "canViewExecutiveSummaryGlobal",
    "canViewExecutiveSummary",
    "canViewOSADeepdive",
    "canViewFeedback",
    "canViewGlossary",
  ],
  CountryLead: [
    "canViewLandingPage",
    "canViewPicosDeepdive",
    "canViewOOSDeepdive",
    "canViewExecutiveSummaryGlobal",
    "canViewExecutiveSummary",
    "canViewOSADeepdive",
    "canViewCountryLeader",
    "canViewFeedback",
    "canViewGlossary",
  ],
};

export default permissions;
