import Head from "next/head";
import OosAlertTable from "@/components/OosAlert/OosAlertTable";
import PicosGrowthTable from "@/components/picosGrowthTable/PicosGPTable";
import LogBookTable from "@/components/logbook/LogBookTable";
import FilterBar from "@/components/FilterBar";
import { withPermission } from "@/hoc";

export default function Actions(): JSX.Element {
  const RenderOsaAlertTable = withPermission(OosAlertTable, [
    "canViewActionPage",
  ]);

  const RenderPicosGrowthTable = withPermission(PicosGrowthTable, [
    "canViewActionPage",
  ]);

  const RenderLogBookTable = withPermission(LogBookTable, [
    "canViewActionPage",
  ]);

  return (
    <>
      <Head>
        <title>Actions | Eddgie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilterBar />
      <main className="section">
        <RenderOsaAlertTable />
      </main>
      <main className="section">
        <RenderPicosGrowthTable />
      </main>
      <main className="section">
        <RenderLogBookTable />
      </main>
    </>
  );
}
