import RenderScoreCard from "@/components/RenderScoreCard";
import Head from "next/head";
export default function Scorecard(): JSX.Element {
  return (
    <>
      <Head>
        <title>Scorecard | Eddgie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="scorecard" className="section-wrapper">
        <RenderScoreCard />
      </main>
    </>
  );
}
